included:
  - AutoRoute
  - AutoRouteTests
  - AutoRouteUITests

identifier_name:
  min_length: 2
  max_length: 45
  excluded:
    - i
    - x
    - y
    - id

large_tuple:
  warning: 10
  error: 30

disabled_rules:
  - file_length
  - trailing_whitespace
  - line_length
