included:
  - AutoRoute
  - AutoRouteTests
  - AutoRouteUITests

line_length:
  warning: 120
  error: 150

identifier_name:
  min_length: 2
  max_length: 45
  excluded:
    - i
    - x
    - y
    - id

large_tuple:
  warning: 10
  error: 30

disabled_rules:
  - trailing_comma
