name: iOS

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ios-app-test:
    permissions:
      contents: read
      checks: write
    uses: ./.github/workflows/xcode-test.yml
    with:
      job_name: iOS App Tests
      scheme: Driveline
      destination: 'platform=iOS Simulator,name=iPhone 17,arch=arm64'
      test_plan: iOS
      coverage_exclude_xctest: "true"
      coverage_exclude_target: MLTrainingDataPrepTool
      artifact_name: test-results
